# Handshake Data Analysis:

**Understanding the Total Addressable Market of potential diverse STEM employees**

In [47]:
import pandas as pd 
import matplotlib.pyplot as plt
plt.style.use('seaborn-dark-palette')
import warnings
warnings.filterwarnings("ignore")

In [48]:
df = pd.read_csv('main_df.csv')
df.head()

,YEAR,MULTYEAR,SAMPLE,SERIAL,CBSERIAL,HHWT,CLUSTER,STATEFIP,STRATA,GQ,...,INCWAGE,State,under_represented,domestic_born,EDU_verbose,is_STEM_degree,Degree,Degree_D,JobRole,stemType
0,2020,2016,202003,6676264,2016000978820,5.15,2020066762643,55,10055,1,...,51776,Wisconsin,0,1,High School,0,NaN,NaN,couriers and messengers,-1
1,2020,2016,202003,4027595,2016000661290,17.51,2020040275953,36,60036,1,...,21573,New York,0,1,High School,0,NaN,NaN,miscellaneous production workers including equipment operators and tenders,-1
2,2020,2017,202003,5156019,2017000181278,6.18,2020051560193,42,370142,1,...,0,Pennsylvania,0,0,Bachelor,0,Criminal Justice and Fire Protection,Criminal Justice and Fire Protection,elementary and middle school teachers,-1
3,2020,2020,202003,6777997,2020000352838,69.01,2020067779973,55,5510155,1,...,52000,Wisconsin,0,1,High School,0,NaN,NaN,credit counselors and loan officers,-1
4,2020,2017,202003,4717146,2017000352033,15.45,2020047171463,39,280039,1,...,40126,Ohio,0,1,High School,0,NaN,NaN,janitors and building cleaners,-1

#### Question 1: How many under-represented persons are there?

In the US in Total as well as working in STEM:

In [ ]:
df['under_represented']